### PR TITLE
Create `Whole` type

### PR DESCRIPTION
**Pull request by joneshf**
Sometimes you want a number that is guaranteed to not be negative.

Let me know if there's anything you'd like to change.

### CODE REVIEW

**Comment by joneshf** [comment]
@Fresheyeball ping

**Comment by joneshf** [comment]
Actually, `Natural` is currently just `Positive Int`. How would you feel about making `Natural` include 0?

**Comment by Fresheyeball** [comment]
I don't think Natural should include zero based on wikipedia. So I like the addition of Whole. I'll merge this, make some changes and release.

**Comment by Fresheyeball** [comment]
Published. Plus I added Prime and a Conversions module.

**Pull request merged**
